safe:        false
auto:        true
port: 4000
baseurl:    /
url: http://localhost:4000

name: Hugo Melo

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
highlighter: rouge
markdown:    kramdown
permalink:   /:title
paginate: 3

comments: true
github: squanto
tinyletter: hugomelo
disqus: hugo-melo

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
