safe:        false
port: 4000
url: http://localhost:4000

name: Hugo Melo

source:      .
destination: ./_site

future:      true
lsi:         false
markdown:    kramdown
permalink:   /:title
highlighter: rouge

github: squanto
tinyletter: hugomelo
incremental: true
rdiscount:
  extensions: []

kramdown:
  input: GFM
  syntax_highlighter: rouge
