safe:        false
port: 4000
baseurl:    /
url: http://localhost:4000

name: Hugo Melo

source:      .
destination: ./_site
# plugins_dir:     ./_plugins

future:      true
lsi:         false
highlighter: rouge
markdown:    kramdown
permalink:   /:title

comments: true
github: squanto
tinyletter: hugomelo
disqus: hugo-melo

incremental: true

rdiscount:
  extensions: []
